### ISSUE TITLE
無法發佈分支，錯誤訊息：Please make sure you have the correct access rights and the repository exists.

### ISSUE THREAD

**Issue by shiunchiu** [eGroupTeam/course-backend#8]
# 背景環境說明

1. Windows 10 家用版
2. 使用SSH連線方式clone GitHub內容 
`git clone git@github.com:eGroupTeam/course-backend.git `
3. 以Git Bash + VScode操作Git
4. 最一開始使用HTTPS連線方式clone，不能Pull,Push，於是轉用SSH連線

# 問題說明
無法Push分支，出現錯誤訊息
`fatal: Could not read from remote repository. Please make sure you have the correct access rights
and the repository exists.`

### 圖1(SSH & HTTPS)
![image](https://user-images.githubusercontent.com/108112302/177009756-67c799ff-f0c1-4476-8f0e-1be96d40b0e8.png)

### 圖2(HTTPS)
![noAccess](https://user-images.githubusercontent.com/108112302/177010064-f11dca5b-2ef0-4f9b-93ee-84bfb8623f6c.png)

### 圖3(SSH & HTTPS)
![permissionDenied](https://user-images.githubusercontent.com/108112302/177010264-02187eac-f5bc-499f-9c50-295c2d809930.png)

# 實際操作

![cannotPushBranch](https://user-images.githubusercontent.com/108112302/177009883-ac89ec2e-910a-4672-8866-07971c9a4a63.gif)

# 已嘗試過的解決方法

1. 最一開始使用https的方式clone項目，一樣不能Push和Pull，決定轉用目前使用的SSH連線方式clone
2. [解決github無法push，requested URL returned error: 403問題](https://123davidbill.medium.com/%E8%A7%A3%E6%B1%BAgithub%E7%84%A1%E6%B3%95push-requested-url-returned-error-403%E5%95%8F%E9%A1%8C-213b08866a38)
3. [Git – GitHub 出現 「Please make sure you have the correct access rights and the repository exists.」](http://jsnwork.kiiuo.com/archives/3147/git-github-%E5%87%BA%E7%8F%BE-%E3%80%8Cplease-make-sure-you-have-the-correct-access-rights-and-the-repository-exists-%E3%80%8D/)
4. [GitHub "fatal: remote origin already exists"](https://stackoverflow.com/questions/10904339/github-fatal-remote-origin-already-exists)

**Comment by jitsungwu** [comment]
兩個可能性:
1.你的帳號沒有權限進行push pull，需要 @a6091731 確認
2.github已經開始進行二階段驗證，需要建立token
https://andy6804tw.github.io/2021/08/14/token-authentication-requirements-for-git-operations/

**Comment by shiunchiu** [comment]
> 兩個可能性: 1.你的帳號沒有權限進行push pull，需要 @a6091731 確認 2.github已經開始進行二階段驗證，需要建立token https://andy6804tw.github.io/2021/08/14/token-authentication-requirements-for-git-operations/

感謝教授！
剛剛已嘗試第二個方法建立token，出現的狀況還是跟一開始一樣，那應該就是帳號還沒有權限push和pull了

**Comment by a6091731** [comment]
是分支權限需要設定，下午會開權限給同學，大家就可以開始推Code~

**Comment by LaiTaiYuan** [comment]
fixed
